modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="slimyboyos"
version="${file.jarVersion}"
displayName="SlimyBoyos"
updateJSONURL="https://updates.blamejared.com/get?n=SlimyBoyos&gv=1.15.2"
authors="Jaredlll08"
description='''
Makes slimes pickup items.
'''